apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: demo-app
  namespace: demo-app
spec:
  interval: 5m
  subscriptions:
  - git:
      repoURL: https://github.com/c-yco/argo-kargo-multicluster-lab.git
      branch: main
      includePaths:
      - manifests/**
      commitSelectionStrategy: NewestFromBranch
  - image:
      repoURL: nginxdemos/hello
      semverConstraint: ^0.3.0
      discoveryLimit: 5
