apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: demo-app
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: demo-app
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/c-yco/argo-kargo-multicluster-lab.git
          checkout:
          - branch: main
            path: ./src
      - uses: kustomize-set-image
        config:
          path: ./src/manifests/overlays/dev
          images:
          - image: nginxdemos/hello
      - uses: git-commit
        config:
          path: ./src
          messageFromSteps:
          - kustomize-set-image
      - uses: git-push
        config:
          path: ./src
          targetBranch: env/dev
      - uses: argocd-update
        config:
          apps:
          - name: demo-app-dev
            namespace: argocd
